name: Deploy Database

on:
  workflow_dispatch:

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --only deploy

      - name: Start PostgreSQL database
        env:
          EDITO_USERNAME: ${{ secrets.EDITO_USERNAME }}
          EDITO_PASSWORD: ${{ secrets.EDITO_PASSWORD }}
          EDITO_CLIENT_ID: ${{ secrets.EDITO_CLIENT_ID }}
          EDITO_PROJECT: ${{ secrets.EDITO_PROJECT }}
        run: make start-database
