name: Start Process

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the process to start"
        required: true
      recipient_email:
        type: string
        description: "Email address to send the report to (optional, will not send if not provided)"
        required: false
      maximum_datasets_to_validate:
        type: number
        description: "Maximum number of datasets to validate (optional, will validate all if not provided)"
        required: false


jobs:
  start-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --only deploy

      - name: Start process
        env:
          EDITO_USERNAME: ${{ secrets.EDITO_USERNAME }}
          EDITO_PASSWORD: ${{ secrets.EDITO_PASSWORD }}
          EDITO_PROJECT: ${{ secrets.EDITO_PROJECT }}
          COPERNICUSMARINE_SERVICE_USERNAME: ${{ secrets.COPERNICUSMARINE_SERVICE_USERNAME }}
          COPERNICUSMARINE_SERVICE_PASSWORD: ${{ secrets.COPERNICUSMARINE_SERVICE_PASSWORD }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          REPORT_RECIPIENT_EMAIL_ADDRESS: ${{ inputs.recipient_email }}
          MAXIMUM_DATASETS_TO_VALIDATE: ${{ inputs.maximum_datasets_to_validate }}
        run: make start-process VERSION="${{ inputs.version }}"
