name: Start Process

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the process to start"
        required: true

jobs:
  start-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --only deploy

      - name: Start process
        env:
          EDITO_USERNAME: ${{ secrets.EDITO_USERNAME }}
          EDITO_PASSWORD: ${{ secrets.EDITO_PASSWORD }}
          EDITO_PROJECT: ${{ secrets.EDITO_PROJECT }}
          EDITO_VAULT_TOKEN: ${{ secrets.EDITO_VAULT_TOKEN }}
        run: make start-process VERSION="${{ inputs.version }}"
